### ISSUE TITLE
AudioTranscription throws Unrecognized file format

### ISSUE THREAD

**Issue by UshaPravinkumar** [forestwanglin/openai-java#10]
Hello,
According to the documentation, the Audio API is compatible. However, upon utilizing the Java API for Audio Transcription, I encounter an error stating "Unrecognized file format." I attempted this with various file formats such as m4a, mp3, mp4, and wav.

`CreateAudioTranscriptionRequest request = CreateAudioTranscriptionRequest.builder().model("whisper-1")
            .filePath(filePath).language("en").responseFormat(ResponseFormat.TEXT).build();
 AudioResponse response = new OpenAiService(token, Duration.ZERO).createAudioTranscription(request);`

> Exception in thread "main" xyz.felh.openai.OpenAiHttpException: Unrecognized file format. Supported formats: ['flac', 'm4a', 'mp3', 'mp4', 'mpeg', 'mpga', 'oga', 'ogg', 'wav', 'webm']
> 	at xyz.felh.openai.OpenAiService.execute(OpenAiService.java:128)
> 	at xyz.felh.openai.OpenAiService.createAudioTranscription(OpenAiService.java:461)
> 	at openai.audio.SpeechToText.main(SpeechToText.java:40)
> Caused by: retrofit2.adapter.rxjava3.HttpException: HTTP 400 
> 	at retrofit2.adapter.rxjava3.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
> 	at retrofit2.adapter.rxjava3.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
> 	at retrofit2.adapter.rxjava3.CallEnqueueObservable$CallCallback.onResponse(CallEnqueueObservable.java:62)
> 	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
> 	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at java.base/java.lang.Thread.run(Thread.java:840)
> 

Is there any resolution available for this problem? Even a temporary workaround would be appreciated.

**Comment by forestwanglin** [comment]
I've fixed this issue. Please get the latest version **3.8.2024032101**.
