### ISSUE TITLE
也没有vision api

### ISSUE THREAD

**Issue by zhouhesheng** [forestwanglin/openai-java#2]
这个同 https://github.com/TheoKanning/openai-java 功能和结构都没有多大差别啊
也都没有vision api

**Comment by forestwanglin** [comment]
-  这个同 https://github.com/TheoKanning/openai-java 功能和结构都没有多大差别啊

是的，这个库和你提到的功能结构的确差不多。在我最开始用的时候，我也本来是计划使用那个SDK的，但是当时居然不支持stream这个参数，我就参考了几个类似的SDK，然后加入对stream的支持。而且每次官方API升级后，这些SDK API都更新的太慢，我自己顺手就更新了，方便自己使用。

- 也都没有vision api

你是指的对应gpt-4-vision-preview这个模型的支持吗？11月10号左右就已经对[ChatMessage](https://github.com/forestwanglin/openai-java/blob/main/core/src/main/java/xyz/felh/openai/chat/ChatMessage.java)进行更新了，里面的ContentItem#imageUrl就是传入图片的参数。具体例子可以参考[OpenAiServiceTest.java](https://github.com/forestwanglin/openai-java/blob/main/service/src/test/java/xyz/felh/openai/OpenAiServiceTest.java)中createChatCompletionWithVision。
