### ISSUE TITLE
这个库在chat模型的token计算上有诸多错误

### ISSUE THREAD

**Issue by CodeInDreams** [forestwanglin/openai-java#3]
与openai返回的token对比发现，几乎各chat模型都有计算方式错误或结果偏差，于是我自己从零建模和编写了token计算工具

你的部分token计算代码有严重错误，这里列举部分：
- vision base64读取
- vision图片缩放
- function call、functions
- tool call、tools
- 0301/0314与0613版本计算差异
- 多个参数（model、functions）组合使用对token计算的影响
- 应使用`encodeOrdinary`来跳过special tokens

由于精力有限我无法在开源代码上提交修改，本issue只是告知绝大部分token计算都有误，请你自己有精力时研究下

**Comment by forestwanglin** [comment]
非常感谢，因为没有看到官方明确的计算方式文档，我是通过自己有限的测试case进行了测试。

不知道你写的计算工具是根据官方文档还是通过自己摸索出来的？

**Comment by forestwanglin** [comment]
感谢，的确不能保证和官方返回一模一样。

可以看到官方的cookbook[How_to_count_tokens_with_tiktoken](https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb)中也是提到

![image](https://github.com/forestwanglin/openai-java/assets/2397372/75307ace-c24e-4fa8-8db9-28cec9add3b4)

也是一个预估值，这个计算方法主要是用来预估发送的一些limit，所以有一点误差不会影响逻辑。

**Comment by forestwanglin** [comment]
token计算不支持 gpt-3.5-turbo-0301

**Comment by forestwanglin** [comment]
我按照官方Demo的计算规则，更新了计算方法。
已经测试的：
- gpt-3.5-turbo(gpt-3.5-turbo-0613/gpt-3.5-turbo-16k-0613)
- gpt-3.5-turbo-1106
- gpt-4-1106-preview
- gpt-4(gpt-4-0613/gpt-4-32k-0613)

更新了funciton的计算规则，具体可参考[FunctionFormat](https://github.com/forestwanglin/openai-java/blob/main/jtokkit/src/main/java/xyz/felh/openai/jtokkit/utils/FunctionFormat.java)

**Comment by forestwanglin** [comment]
More solved issue about token calculate issues can be found issue #4.
