### ISSUE TITLE
找不到最新版本

### ISSUE THREAD

**Issue by linyours** [forestwanglin/openai-java#6]
您好大佬,在maven仓库找不到最新的版本,请问在哪可以找到?
<img width="738" alt="image" src="https://github.com/forestwanglin/openai-java/assets/71416178/e11ecf97-87e6-496b-bcd0-f18b40ca21bc">

**Comment by forestwanglin** [comment]
我刚刚发布了一个新的版本`3.7.20240130`到Maven Central，过几个小时应该就可以看到了。

I've just released a new version `3.7.20240130` to maven central. You can find it as soon as it is updated.
